

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1967
      POSTGRES_DB: scavengerhunt
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scavengerhunt"]
      interval: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:1967@db:5432/scavengerhunt
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"         
    volumes:
      - ./frontend:/app     
      - /app/node_modules   

volumes:
  db_data:
