version: '3.8'

services:
  sqlserver:
    container_name: scavenger-hunt-db
    image: mysql:latest
    env_file: .env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  migrations:
    container_name: service-migrations
    image: service-migrations
    env_file: .env
    build:
      context: .
      dockerfile: dockerfile.migrations
      target: migrations
    depends_on:
      - sqlserver
    command: ["dotnet-ef", "database", "update", "--project", "ScavengerHunt.Infrastructure/", "--startup-project", "ScavengerHunt.Api/"]
    environment:
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=${MYSQL_DATABASE};User=root;Password=${MYSQL_ROOT_PASSWORD}

  api:
    container_name: scavenger-hunt-api
    env_file: .env
    build:
      context: .
      dockerfile: dockerfile.api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=${MYSQL_DATABASE};User=root;Password=${MYSQL_ROOT_PASSWORD}
    ports:
      - "7105:7105"