version: '3.8'

services:
  # Hunts Api Setup
  hunts-api:
    container_name: scavenger-hunts-api
    env_file: .env
    build:
      context: .
      dockerfile: hunts.api.dockerfile
    depends_on:
      - hunts-db
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__HuntsDbConnection: Server=hunts-db;Database=${HUNTS_DB_NAME};User=root;Password=${HUNTS_DB_ROOT_PWD}
      RabbitMQHost: scavenger-msg-bus
    ports:
      - "5000:7105"

  # Hunts Database Setup
  hunts-db:
    container_name: scavenger-hunts-db
    image: mysql:latest
    env_file: .env
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${HUNTS_DB_ROOT_PWD}
      MYSQL_DATABASE: ${HUNTS_DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Hunts Migrations Setup
  hunts-migrations:
    container_name: scavenger-hunts-migrations
    image: scavenger-hunts-migrations
    env_file: .env
    build:
      context: .
      dockerfile: hunts.migrations.dockerfile
      target: migrations
    depends_on:
      - hunts-db
    command: ["dotnet-ef", "database", "update", "--project", "Hunts.Infrastructure/", "--startup-project", "Hunts.Api/"]
    environment:
      ConnectionStrings__HuntsDbConnection: Server=hunts-db;Database=${HUNTS_DB_NAME};User=root;Password=${HUNTS_DB_ROOT_PWD}

  # Participants Api Setup
  participants-api:
    container_name: scavenger-participants-api
    env_file: .env
    build:
      context: .
      dockerfile: participants.api.dockerfile
    depends_on:
      - participants-db
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ParticipantsDbConnection: Server=participants-db;Database=${PARTICIPANTS_DB_NAME};User=root;Password=${PARTICIPANTS_DB_ROOT_PWD}
      RabbitMQHost: scavenger-msg-bus
    ports:
      - "5100:7105"

  # Participants Database Setup
  participants-db:
    container_name: scavenger-participants-db
    image: mysql:latest
    env_file: .env
    ports:
      - 3399:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${PARTICIPANTS_DB_ROOT_PWD}
      MYSQL_DATABASE: ${PARTICIPANTS_DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Participants Migrations Setup
  participants-migrations:
    container_name: scavenger-participants-migrations
    image: scavenger-participants-migrations
    env_file: .env
    build:
      context: .
      dockerfile: participants.migrations.dockerfile
      target: migrations
    depends_on:
      - participants-db
    command: ["dotnet-ef", "database", "update", "--project", "Participants.Infrastructure/", "--startup-project", "Participants.Api/"]
    environment:
      ConnectionStrings__ParticipantsDbConnection: Server=participants-db;Database=${PARTICIPANTS_DB_NAME};User=root;Password=${PARTICIPANTS_DB_ROOT_PWD}

  # RabbitMQ Message Bus
  rabbitmq:
    container_name: 'scavenger-msg-bus'
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672